# -*- coding: utf-8 -*-
"""Ascii Art.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bkNCsDBjFscfagWkh8ly-jLnz0iPaqZr
"""

import cv2 #to view image
import numpy as np
import sys

"""**Keep The Image Simple**


---


From my experience, the process is very iterative
You may need to change your symbols often and threshold until you find something that you're comfortable with. Just have fun with it.
"""

#This is our image
from google.colab import files
from IPython import display

uploaded = files.upload()

display.Image("nike-swoosh-wikipedia.jpeg",
              width=1000)

#Decide what symbols you want to use
#I know this is going to look awful,  but it's worth trying
symbols = ["N", "•", "_", "«"]
threshold_list =[0, 5, 10, 150000, 20000000]

# create a function to change the image to ascii 
def image_to_ascii(image):
  "returns an image that is encoded to ascii"

  #First resize the image 
  #Change resizing parameters to fit what you need 
  height, width = image.shape
  new_height = int(height/20)
  new_width = int(width/20)

  #use the resizing parameters to get a new sized image using cv2.resize()
  resized_image = cv2.resize(image, (new_width, new_height))

  #Create a numpy array of zeros that is the new size of the image. Remember that the image is now an ascii object with a shape
  thresh_image = np.zeros(resized_image.shape)

  for i, threshold in enumerate(threshold_list):
        # assign corresponding values according to the index of threshold applied
        thresh_image[resized_image > threshold] = i
  return thresh_image

def print_out_ascii(array):
    """prints the coded image with symbols"""

    for row in array:
        for e in row:
        	# select symbol based on the type of coding
            print(symbols[int(e) % len(symbols)], end="")
        print()

image_path = "nike-swoosh-wikipedia.jpeg"

if __name__ == "__main__":

    if len(sys.argv) < 2:
        print("Image Path not specified : Using sample_image.png\n")
        # image_path = "nike-swoosh-wikipedia.jpeg"  # default image path

    if len(sys.argv) == 2:
        print("Using {} as Image Path\n".format(sys.argv[1]))
        image_path = sys.argv[1]

    image = cv2.imread(image_path, 0)  # read image

    ascii_art = image_to_ascii(image)
    print_out_ascii(ascii_art)

"""# Ascii Art using the Ascii Library
---


"""

